### ISSUE TITLE
Boost Cake documentation

### ISSUE THREAD

**Issue by muhammadcahya** [slywalker/cakephp-plugin-boost_cake#1]
In the Read Me I can't find complete documentation, for all feature in this plugin
Is it final?
Or its documentation like in https://github.com/slywalker/TwitterBootstrap

**Comment by slywalker** [comment]
It's mean this?
http://slywalker.github.io/cakephp-plugin-boost_cake/

**Comment by muhammadcahya** [comment]
Yes, I mean add http://slywalker.github.io/cakephp-plugin-boost_cake/bootstrap2.html to ReadMe for offline user, 
Thanks for a Good plugin, 
#It's there a combined with ajax/js helper ?, like $this->Js->submit/link ?
#or something like $this->Paginator->options(array('update' => '#content')); ?

**Comment by slywalker** [comment]
You can read offline https://github.com/slywalker/cakephp-plugin-boost_cake/blob/master/View/BoostCake/bootstrap2.ctp

I have no intention to ajax/js helper.

**Comment by muhammadcahya** [comment]
Ok, It's fix/final version from https://github.com/slywalker/TwitterBootstrap ?
#closed :)

**Comment by slywalker** [comment]
Yes.
TwitterBootstrap has been too fat.
There was a need to be slim plugin in order to cope with Bootstrap3.

**Comment by taleeb35** [comment]
How to disappear flash messages in this plugin?
