### ISSUE TITLE
No bootstrap theme for bake

### ISSUE THREAD

**Issue by gmenel** [slywalker/cakephp-plugin-boost_cake#11]
In TwitterBootstrap the theme baked nicer views, in specific index.ctp "Actions".

It is allot of work to modify those by hand and would be nice if bake template can be included in BoostCake.

Current:

``` html
<div class="actions">
    <h3><?php echo __('Actions'); ?></h3>
    <ul>
```

Old TwitterBootstrap:

``` html
    <div class="span3">
        <div class="well" style="padding: 8px 0; margin-top:8px;">
        <ul class="nav nav-list">
            <li class="nav-header">
```

**Comment by slywalker** [comment]
I'm worried about is making a template.
Because it because shall corresponding to Bootstrap3. I think I put a little time.

**Comment by muhammadcahya** [comment]
I do not really understand what you mean guillaumenel

Maybe you are referring to, is CAKESTRAP
http://drawrdesign.com/twitter-bootstrap-for-cakephp
https://github.com/Rhym/cakeStrap

but the preparation still making manual in form section. Like control-group, etc, I think when cakestrap using this best bootstrap plugin will make the code more simple.

Hope it helps :)

Thanks
