### ISSUE TITLE
No LinkHelper / ButtonHelper ?

### ISSUE THREAD

**Issue by Kareylo** [slywalker/cakephp-plugin-boost_cake#12]
Hi, i'd like to know if you'll make a helper for links and buttons.
Will be nice to do something like that : 

``` html
<a href="/Link/To/User/Profile"><span><i class="icon-user"></i> Username</span></a>
```

Without a big code like : 

``` php
<?= $this->Html->link(
   '<span><i class="icon-user"></i> ' . $post->Users->username . '</span>', 
   array(
      'controller' => 'users', 
      'action' => 'account', 
      $post->users_id
   ), 
   array('escape' => false)); ?>
```

**Comment by slywalker** [comment]
That is not how usable how convenient, make the impossible possible is the purpose of this plug-in.
I think it is better to realize each project is the good convenient usage.

By the way, my writing is this

``` php
<a href="<?php echo Router::url(array(
    'controller' => 'users', 
    'action' => 'account', 
    $post->users_id
)); ?>">
    <span><i class="icon-user"></i> <?php echo $post->Users->username; ?></span>
</a>
```

**Comment by angelxmoreno** [comment]
@slywalker I understand what you are saying, but the whole point of using helpers is to add rapid application development to the view layer. I think the community coming from the old Plugin would want to see Html helper functions for quickly generating bootstrap components. I think doing something like 

```
$this->Html->icon('user');
```

is much cleaner than having 

```
<span><i class="icon-user">
```

Also, extending the BoostCakeHtmlHelper to change how icons are created would make it easier to change all the html produced on an application that uses hundreds of icons across many views. The point is to make it easier and faster to change rendered html on an entire application by simply going to one location.

I can submit a PR with more Bootstrap components as Helpers for this convenience if you agree.

**Comment by lucasff** [comment]
Hi @slywalker, I agree with @angelxmoreno.
