### ISSUE TITLE
BoostCake not loading

### ISSUE THREAD

**Issue by ghost** [slywalker/cakephp-plugin-boost_cake#15]
I have followed the steps of the [documentation](http://slywalker.github.io/cakephp-plugin-boost_cake/)
Steps:
1. Use Composer to install BoostCake. It's now in the "Plugin" folder.
2. Add "CakePlugin::loadAll();" to bootstrap.php. DebugKit is loading.
3. Try to go to "localhost/projectname/boostcake/" but CakePHP says that the controller is missing.

What am I doing wrong? If any log or configuration files are needed just say.

**Comment by slywalker** [comment]
Please access "localhost/projectname/boost_cake/"

**Comment by ghost** [comment]
Okay it's working now...the documentation isn't very helpful for beginners, but thanks for helping. ;)

**Comment by VaibhaviMadhuresh** [comment]
1. Use Composer to install BoostCake. It's now in the "Plugin" folder.
2. Add "CakePlugin::loadAll();" to bootstrap.php. DebugKit is loading.
3. Try to go to1. Use Composer to install BoostCake. It's now in the "Plugin" folder.
4. Add "CakePlugin::loadAll();" to bootstrap.php. DebugKit is loading.
5. Try to go to "localhost/projectname/boostcake/" but CakePHP says that the controller is missing.

What am I doing wrong? If any log or configuration files are needed just say. but CakePHP says that the controller is missing.

What am I doing wrong? If any log or configuration files are needed just say.

**Comment by vasconce7os** [comment]
slywalker also helped me, I was having the same problem

**Comment by angelxmoreno** [comment]
knowing CakePHP, especially how plugin routes work is a prerequisite of using this plugin. This plugin's documentation is not going to cover plugin routes. Please review how plugins are routed in the CakePHP manual.

**Comment by pappugotya123** [comment]
Error: BoostCakeController could not be found.

I'm using linux command line, no gui, I did what you suggested for first query but still it says that BoostCakeController is missing..please help me out..

**Comment by vnpnlz** [comment]
I also having the same error. I am using Linux (Ubuntu). I also tried what is written on the documentation and still it doesn't work.
