### ISSUE TITLE
FormHelper radio input problem

### ISSUE THREAD

**Issue by gabrielfigueroa** [slywalker/cakephp-plugin-boost_cake#18]
echo $this->Form->input('active', array(
    'label' => 'Active?',
    'type' => 'radio',
    'multiple' => false,
    'options' => array('1' => 'Yes', '0' => 'No'),
));     

This used to generate two radio inputs, now it generates two labels but only one radio input. I changed the value of No to something other than zero and it still only displays one radio.

**Comment by slywalker** [comment]
Do you expect what output HTML?

**Comment by gabrielfigueroa** [comment]
It used to display a label with a radio input for each option provided. After the migration into BoostCake it displays only one radio input even when it contains multiple options. The text for the options is displayed but only one radio. I switched to using checkboxes with single options as a work around until this got fixed.

**Comment by awebdeveloper** [comment]
here is the issue 

```
echo $this->Form->input('account_status');
```

generates

```
<div class="form-group">
<div class="input radio">
<fieldset><legend>Account Status</legend>
<input type="hidden" name="data[User][account_status]" id="UserAccountStatus_" value="">
<label class="form-control" for="UserAccountStatusActive"><input type="radio" name="data[User][account_status]" id="UserAccountStatusActive" value="active"> active</label>
<label class="form-control" for="UserAccountStatusInactive"><input type="radio" name="data[User][account_status]" id="UserAccountStatusInactive" value="inactive"> inactive</label>
</fieldset>
</div>
</div>
```

Notice 2 divs .... Issue seams to be in _divoptions functions 

commenting below line solves it

```
$this->_divOptions = parent::_divOptions($divOptions);
```
