### ISSUE TITLE
How to Change Labeling style for checkbox

### ISSUE THREAD

**Issue by muhammadcahya** [slywalker/cakephp-plugin-boost_cake#3]
For my interest helper I found something
I have code :

<pre>$this->Form->input('disabled');</pre>

and generate view :
![cakephp the rapid development php framework posts](https://f.cloud.github.com/assets/4241620/713772/be9a94b4-dedb-11e2-9c41-0af515a1b983.png)

in first disabled field i use above code, but the label generated besides input form

How to generated like the second field, with label in contain of control-group. ?
# The field type in my database is tinyint

**Comment by slywalker** [comment]
Now, I push master.
Add checkboxDiv option and sample, test case.

Please, pull.

**Comment by muhammadcahya** [comment]
Thanks, I do not understand what you mean "pull"
Hhhee :p

**Comment by slywalker** [comment]
"pull" is update (・∀・)
