### ISSUE TITLE
Label in horizontal form right

### ISSUE THREAD

**Issue by Zwaen91** [slywalker/cakephp-plugin-boost_cake#68]
When I add the text for the label like in your example below the classes are not applied to the label any more.

<?php echo $this->Form->create('BoostCake', array(
    'inputDefaults' => array(
        'div' => 'form-group',
        'label' => array(
            'class' => 'col col-md-3 control-label'
        ),
        'wrapInput' => 'col col-md-9',
        'class' => 'form-control'
    ),
    'class' => 'well form-horizontal'
)); ?>
<?php echo $this->Form->input('remember', array(
    'wrapInput' => 'col col-md-9 col-md-offset-3',
    'label' => 'Remember me',
    'class' => false
)); ?>

**Comment by houseoftech** [comment]
You can supply both so the class is not overwritten:

```
'label' => array(
     'text' => 'Remember Me',
     'class' => 'col col-md-3 control-label'
)
```

Or, @slywalker here is a fix: https://github.com/houseoftech/cakephp-plugin-boost_cake/commit/1f31c320fb4cb0cef6c90a6caec10e8768b49d7d

**Comment by olivMertens** [comment]
9 years !! after :)
