### ISSUE TITLE
Date/datetime field custom

### ISSUE THREAD

**Issue by muhammadcahya** [slywalker/cakephp-plugin-boost_cake#7]
If I have a field in database with date / datetime type cake is generated with year month date, hours, minute, pm/am combobox field.

Can the default in this helper set width to this field is proporsional, no smaller or bigger.

Or set option to do or not generate field to year month date, hours, minute, pm/am combobox field with one field. if I use js datepicker from vendor i chose.

**Comment by slywalker** [comment]
I think it's best that you will use the datetime picker of favorite's.

**Comment by slywalker** [comment]
Cool datetime picker [Bootstrap Date/Time Picker](http://tarruda.github.io/bootstrap-datetimepicker/)

**Comment by muhammadcahya** [comment]
1. Datepicker may wear better, but it would be better to correct the default date time field in this plugin :)
2. Is when using datepicker will not interfere with cakephp validation format ?
   ![cakephp the rapid development php framework posts](https://f.cloud.github.com/assets/4241620/729671/431b0de8-e23a-11e2-84f3-c7770d1aca58.png)

**Comment by slywalker** [comment]
1. You designate `width:auto;` at style of input.
2. You can add custom validate in model. [Data Validation — CakePHP Cookbook v2.x documentation](http://book.cakephp.org/2.0/en/models/data-validation.html#custom-validation-rules)

**Comment by muhammadcahya** [comment]
Yes, that's my way now. I mean if it can be made as a default ?

**Comment by slywalker** [comment]
Based on the reflection of TwitterBootstrapPlugin, BoostCake is the processing of the minimum required in the initial dare.
However, that policy will change how the Bootstrap CSS depending on whether the change.

**Comment by muhammadcahya** [comment]
Closed :)
