### ISSUE TITLE
Truncate Method is missing

### ISSUE THREAD

**Issue by ismak50** [slywalker/cakephp-plugin-boost_cake#77]
Hi to you,
I am using your plug in in my cake dev. it is very useful.
When I try to truncate some string in a view
echo $this->Html->truncate(nl2br(h($post['Post']['content'])),20);
I have this error:
Method BoostCakeHtmlHelper::truncate does not exist [CORE/Cake/View/Helper.php, line 231]

I'm using cakephp v2.6

I don't understand because you extend your helper from HtmlHelper.
Thank you

**Comment by olivMertens** [comment]
hi,
Because the truncate is based on the Text Helper, not the Html.
i hope it will be helpfull.
++

**Comment by ismak50** [comment]
i was returning to this issue to say the same thing.
10x xam1311

Have a nice day !

**Comment by ismak50** [comment]
i was returning to this forum for say the same thing.
10x xam1311

Have a nice day !
