### ISSUE TITLE
Changes from TwitterBootstrap plugin?

### ISSUE THREAD

**Issue by CostaC** [slywalker/cakephp-plugin-boost_cake#8]
Hi, what has changed with the move to BoostCake from https://github.com/slywalker/TwitterBootstrap ?

**Comment by slywalker** [comment]
TwitterBootstrap plugin has been too fat.
Because I asked for ease of use, versatility gone it. Further, it was broken partly functions FormHelper.

Specifying the option will be this plugin many, but I general use.
Convenience of most big thing corresponding to Bootstrap3.
