### ISSUE TITLE
add atributte multiple to combo box in HABTM field relations

### ISSUE THREAD

**Issue by muhammadcahya** [slywalker/cakephp-plugin-boost_cake#9]
In my project I use HABTM relation, in default form helper cakephp, the field is generated to select(combo box) with added multiple = multiple, so output is multiple select. But in this plugin not added multiple by default, so the output is combo box.

for example

<pre>$this->Form->input('tag');</pre>

And in this plugin can be better, if the field relation is HABTM the default is added multiple :)

**Comment by slywalker** [comment]
Because it is made with the current specifications in order to determine the versatility, there is no plan of implementation. :smirk:
